# Generated by Django 3.2.4 on 2021-07-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('domaine', models.CharField(max_length=100)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('type_publication', models.CharField(default='Demande', max_length=100)),
                ('periode', models.IntegerField()),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
    ]
